export const TONGHOP_START_LEVEL = 301;
export const tonghopIds = [301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351];
export const tonghopEmojis = ["⭐","🦈","👶","🇻🇳","🎃","👦","🦩","🐻","🍉","🐆","🐦","🌊","🐴","👧","📸","🐱","🚀","⚡","👽","🥋","🐥","🌈","😠","🦖","💜","🦄","🦊","⚽","🟡","🎥","☀️","🔥","❄️","🦇","👾","🤖","💨","🦈","🐧","👹","😈","⚡","🚁","🚓","⚽","⚔️","🎵","📺","🌳","🖤","👧"];
export const tonghopNames = [
  "2 Con Sao Biển Mỉm Cười",
  "Baby Shark",
  "Bebefinn Vui Vẻ",
  "Bé Gái Cầm Lá Cờ Việt Nam",
  "Bí Ngô Halloween Phù Thủy",
  "Chaien Vui Vẻ",
  "Chim Hồng Hạc Lộng Lẫy",
  "Chopper Trong One Piece",
  "Cocomelon Cute",
  "Con Báo Đốm Dễ Thương",
  "Con Chim Sẻ",
  "Con Sứa Bé Nhỏ",
  "cá ngựa",
  "Cô Bé Masha và Gấu",
  "Deadpool Chụp Ảnh",
  "doraemon và dorami",
  "Doremon Đang Bay",
  "Flash Cute",
  "Frieza Cực Ngầu",
  "Goku Nhỏ Bé",
  "Gà Con Đáng Yêu",
  "Hello Kitty Ngồi Dưới Cầu Vồng",
  "Jadoo Tức Giận",
  "Khủng Long Ba Sừng Ngộ Nghĩnh",
  "Kuromi",
  "Kì Lân Và Cầu Vồng",
  "Lucario Đang Chiến Đấu",
  "Messi và Quả Bóng",
  "Minion Bob Đang Cười",
  "Mr Beast",
  "Mặt Trời Mỉm Cười",
  "Na Tra Vui Vẻ",
  "Ngao Bính",
  "Người Dơi Dễ Thương",
  "Người Ngoài Hành Tinh",
  "Người Sắt Iron Man",
  "Nhím sonic",
  "Pinkfong Dễ Thương",
  "Pororo Tinh Nghịch",
  "Quái Vật Nhỏ Dễ Thương",
  "quái vật đáng yêu",
  "Raichu Mỉm Cười",
  "Robocar Poli Helly",
  "Robocar Poli",
  "Ronaldo Ngộ Nghĩnh",
  "Roronoa Zoro Vui Nhộn",
  "Sprunki Ngộ Nghĩnh",
  "Titan TV Man",
  "Totoro",
  "Venom Đáng Yêu",
  "Xuka Vui Vẻ"
];

// Dữ liệu SVG các tranh Tổng hợp đã tách ra public/coloring/tonghop.json (fetch động khi bé mở tranh).
